name: CMake Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          pkg-config \
          libgstreamer1.0-dev \
          libgstreamer-plugins-base1.0-dev \
          libgstreamer-plugins-good1.0-dev \
          libjsoncpp-dev \
          libcurl4-openssl-dev \
          libssl-dev \
          libpaho-mqttpp-dev \
          libpaho-mqtt-dev

    - name: Create build directory
      run: mkdir -p build

    - name: Configure CMake
      working-directory: ./build
      run: cmake .. -DCMAKE_BUILD_TYPE=Release

    - name: Build project
      working-directory: ./build
      run: make -j$(nproc)

    - name: Run basic test (optional)
      working-directory: ./build
      run: |
        if [ -f bin/eplayer ]; then
          echo "Build successful, executable exists"
          ./bin/eplayer --help || true
        else
          echo "Executable not found!"
          exit 1
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: eplayer-binary
        path: build/bin/eplayer
        if-no-files-found: error
